export const insuranceForms = [
  {
    formName: "Medi Assist",
    cashlessFormId: 60,
    currentMedicalInsuranceCompanyName: "MEDI ASSIST",
    payerName: "Asif Khan",
    tollFreePhoneNumber: "9384434576",
    tollFreeTax: "9384434576",
    contactNoOfAttendingRelative: "9384434576",
    currentMedicalCompanyDetails: "",
    hospitalFaxNo: "1505",
    hospitalPhoneNo: "1505",
    rheumatoidArthritisSince: "N/A",
    rheumatoidArthritisSinceTf: "N/A",
    rheumatoidArthritisRemarks: "No rheumatoid disease",
    cerebroVascularSince: "N/A",
    cerebroVascularSinceTf: "N/A",
    cerebroVascularRemarks: "No cerebro vascular disease",
    liverDiseaseSince: "N/A",
    liverDiseaseSinceTf: "N/A",
    liverDiseaseRemarks: "No liver disease",
    kidneyDiseaseSince: "N/A",
    kidneyDiseaseSinceTf: "N/A",
    kidneyDiseaseRemarks: "No liver disease",
    gradeOfSurgery: "Grade II – Intermediate",
    policyId: 12345,
    groupId: 54321,
    corporateId: 7890,
    corporate: "Apex Solutions Group",
    groupName: "Apex Solutions Group",
    corporateEmployeeId: 1001,
    employeeName: "Asif Khan",
    relation: "Self",
    patientName: "Asif",
    patientId: 5001,
    uhid: "5645654",
    contactNo: "7646777891",
    dateOfBirth: "02/06/2020 00:00:00",
    gender: "male",
    age: "5 Y",
    insuranceName: "HealthCare Plus",
    giveDetails: "Patient experienced intermittent fever and body ache for 3 days. Initial diagnosis suggested viral infection. Further tests confirmed no bacterial involvement. Treatment initiated with antipyretics and rest.",
    additionalPayerName: "Family",
    additionalPolicyNumber: "POL1234567",
    email: "asif@gmail.com",
    occupation: "Business Man",
    emergencyContact: "9876543210",
    insuredIdCardNo: "ID123456789",
    policyNumber: "POL09876543219876543210",
    employeeId: "EMP100100",
    memberId: "MEM1001",
    currentlyDoYouHaveAnyOtherMedicalClaimHealthInsurance: "no",
    doYouHaveAFamilyPhysician: "Yes",
    currentPatientAddress: "123, Main Street, Bhubaneswar",
    nameOfTheTreatingDoctor: "Dr. Rajesh Kumar",
    doctorContactNo: "0123456789",
    relevantClinicalFindings: "Normal clinical findings",
    natureOfIllnessWithPresentingComplaints: "Fever, cough, and cold",
    durationOfPresentIllness: "3 days",
    doctorDateOfFirstConsultation: "10/07/2025 09:00:00",
    pastHistoryPresentIllness: "No significant past illness",
    provisionalDiagnosis: "Viral Fever",
    icd10Code: "J11",
    ifInvestigativeOfMedicalManagementProvideDetails: "Blood tests and X-ray",
    routeOfDrugAdministration: "Heart disease",
    proposedLineOfTreatment: "Medical management with antipyretics",
    surgicalNameOfSurgery: "N/A",
    icd10PcsCode: "N/0DTJ0ZZ",
    ifOtherTreatmentDetails: "None",
    howDidInjuryOccur: "N/A",
    dateOfInjury: "01/01/1900 00:00:00",
    isItRta: "no",
    reportedToPolice: "no",
    firNo: "365",
    injuryDueToAlcoholConsumption: "no",
    testsConductedToEstablish: "no",
    expectedDateOfDelivery: "01/01/1900 00:00:00",
    maternityG: "10",
    maternityP: "20",
    maternityL: "30",
    maternityA: "40",
    dateAndTimeOfAdmission: "15/07/2025 10:00:00",
    expectedNoOfDaysStayInHospital: "3",
    isThisAEmergencyOrPlannedEvent: "an emergency",
    roomType: "General Ward",
    perDayRoomRentNursingServiceCharges: "1500",
    expectedCostForInvestigationDiagnostics: "2000",
    icuCharges: "220",
    otCharges: "11230",
    professionalFeesSurgeonAnesthetistFeesConsultationCharges: "1000",
    medicinesConsumablesCostOfImplantsIfApplicablePleaseSpecify: "500",
    otherHospitalExpenses: "1000",
    allInclusivePackageChargesIfAnyApplicable: "22220",
    sumTotalExpectedCostOfHospitalization: "5000",
    nameOfTheHospital: "Sum Hospital",
    hospitalLocation: "Bhubaneswar",
    hospitalId: "4",
    hospitalMobileNo: "8768867886",
    hospitalEmail: "asif@gmail.com",
    hospitalSumTotalExpectedCostOfHospitalization: "5000",
    dateOfAdmission: "15/07/2025 10:00:00",
    idCardNumber: "ID10001",
    address: "Plot-11, Bhubaneswar, Odisha, 751001",
    duration: "3 days",
    city: "Bhubaneswar",
    state: "Odisha",
    pincode: "751001",
    investigation: "Blood tests, X-ray",
    patientPanNumber: "ABCDE1234F",
    tariff: "Standard",
    rate: "1500",
    surgeryCode: "N/A",
    sumInsured: "100000",
    rohiniId: "R1234",
    dateOfFirstConsultation: "10/07/2025 09:00:00",
    findings: "Mild fever, no complications",
    primaryMember: "Asif Khan",
    familyPhysicianName: "Dr. Meena Singh",
    familyPhysicianContactNumber: "0987654321",
    specialCase: false,
    pastHistoryOfPresentAilment: false,
    intensiveCare: "No",
    presentAilmentDueToPed: false,
    presentAilmentDuration: "311",
    daysInIcu: "10",
    diabetesSince: "15/08/2025",
    diabetesSinceTf: true,
    diabetesRemarks: "No diabetes history",
    heartDiseaseSince: "N/A",
    heartDiseaseSinceTf: true,
    heartDiseaseRemarks: "No heart disease",
    hyperlipidemiasSince: "N/A",
    hyperlipidemiasSinceTf: true,
    hyperlipidemiasRemarks: "No hyperlipidemia",
    osteoarthritisSince: "03/2021",
    osteoarthritisSinceTf: "true",
    osteoarthritisRemarks: "Mild knee arthritis",
    hypertensionSince: "04/2022",
    hypertensionSinceTf: true,
    hypertensionRemarks: "Under control",
    asthmaCopdBronchitisSince: "N/A",
    asthmaCopdBronchitisSinceTf: true,
    asthmaCopdBronchitisRemarks: "No respiratory conditions",
    cancerSince: "12-12-2012",
    cancerSinceTf: true,
    cancerRemarks: "No cancer history",
    alcoholDrugabuseSince: "N/A",
    alcoholDrugabuseSinceTf: true,
    alcoholDrugabuseRemarks: "No history of abuse",
    hivstdSince: "N/A",
    hivstdSinceTf: true,
    hivstdRemarks: "No HIV/STD",
    anyOtherailmentSince: "N/A",
    anyOtherailmentSinceTf: "N/A",
    anyOtherailmentRemarks: "No other ailments",
    clinicalFindings: "No abnormality detected",
    otherTreatments: "None",
    dateAndTimeOfSignature: "17/07/2025 15:10:00",
    nameOfTreatingDoctor: "Dr. Rajesh Kumar",
    doctorQualification: "BDS, MDS",
    registrationNumberWithStateCode: "30AB1234",
    hospitalDateAndTimeOfSignature: "17/07/2025 15:15:00",
    documentDetails: "All documents submitted successfully",
    status: "submitted",
    active: true,
    deleted: false,
    createTs: "17/07/2025 15:11:20",
    updateTs: "17/07/2025 15:11:20",
    aggregatorCase: false,
    diabetes: false,
    hypertension: false,
    heartDisease: false,
    hyperlipidemias: false,
    osteoarthritis: false,
    asthmaCopdBronchitis: false,
    cancer: false,
    alcoholDrugabuse: false,
    hivstd: false,
    anyOtherailment: false
  },
  {
    formName: "FHPLMedical",
    cashlessFormId: 60,
    currentMedicalInsuranceCompanyName: "FHPL MEDICAL",
    payerName: "Asif Khan",
    tollFreePhoneNumber: "9384434576",
    tollFreeTax: "9384434576",
    contactNoOfAttendingRelative: "9384434576",
    currentMedicalCompanyDetails: "",
    hospitalFaxNo: "1505",
    hospitalPhoneNo: "1505",
    rheumatoidArthritisSince: "N/A",
    rheumatoidArthritisSinceTf: "N/A",
    rheumatoidArthritisRemarks: "No rheumatoid disease",
    cerebroVascularSince: "N/A",
    cerebroVascularSinceTf: "N/A",
    cerebroVascularRemarks: "No cerebro vascular disease",
    liverDiseaseSince: "N/A",
    liverDiseaseSinceTf: "N/A",
    liverDiseaseRemarks: "No liver disease",
    kidneyDiseaseSince: "N/A",
    kidneyDiseaseSinceTf: "N/A",
    kidneyDiseaseRemarks: "No liver disease",
    gradeOfSurgery: "Grade II – Intermediate",
    policyId: 12345,
    groupId: 54321,
    corporateId: 7890,
    corporate: "Apex Solutions Group",
    groupName: "Apex Solutions Group",
    corporateEmployeeId: 1001,
    employeeName: "Asif Khan",
    relation: "Self",
    patientName: "Asif",
    patientId: 5001,
    uhid: "5645654",
    contactNo: "7646777891",
    dateOfBirth: "02/06/2020 00:00:00",
    gender: "male",
    age: "5 Y",
    insuranceName: "HealthCare Plus",
    giveDetails: "Patient experienced intermittent fever and body ache for 3 days. Initial diagnosis suggested viral infection. Further tests confirmed no bacterial involvement. Treatment initiated with antipyretics and rest.",
    additionalPayerName: "Family",
    additionalPolicyNumber: "POL1234567",
    email: "asif@gmail.com",
    occupation: "Business Man",
    emergencyContact: "9876543210",
    insuredIdCardNo: "ID123456789",
    policyNumber: "POL09876543219876543210",
    employeeId: "EMP100100",
    memberId: "MEM1001",
    currentlyDoYouHaveAnyOtherMedicalClaimHealthInsurance: "no",
    doYouHaveAFamilyPhysician: "Yes",
    currentPatientAddress: "123, Main Street, Bhubaneswar",
    nameOfTheTreatingDoctor: "Dr. Rajesh Kumar",
    doctorContactNo: "0123456789",
    relevantClinicalFindings: "Normal clinical findings",
    natureOfIllnessWithPresentingComplaints: "Fever, cough, and cold",
    durationOfPresentIllness: "3 days",
    doctorDateOfFirstConsultation: "10/07/2025 09:00:00",
    pastHistoryPresentIllness: "No significant past illness",
    provisionalDiagnosis: "Viral Fever",
    icd10Code: "J11",
    ifInvestigativeOfMedicalManagementProvideDetails: "Blood tests and X-ray",
    routeOfDrugAdministration: "Heart disease",
    proposedLineOfTreatment: "Medical management with antipyretics",
    surgicalNameOfSurgery: "N/A",
    icd10PcsCode: "N/0DTJ0ZZ",
    ifOtherTreatmentDetails: "None",
    howDidInjuryOccur: "N/A",
    dateOfInjury: "01/01/1900 00:00:00",
    isItRta: "no",
    reportedToPolice: "no",
    firNo: "365",
    injuryDueToAlcoholConsumption: "no",
    testsConductedToEstablish: "no",
    expectedDateOfDelivery: "01/01/1900 00:00:00",
    maternityG: "10",
    maternityP: "20",
    maternityL: "30",
    maternityA: "40",
    dateAndTimeOfAdmission: "15/07/2025 10:00:00",
    expectedNoOfDaysStayInHospital: "3",
    isThisAEmergencyOrPlannedEvent: "an emergency",
    roomType: "General Ward",
    perDayRoomRentNursingServiceCharges: "1500",
    expectedCostForInvestigationDiagnostics: "2000",
    icuCharges: "220",
    otCharges: "11230",
    professionalFeesSurgeonAnesthetistFeesConsultationCharges: "1000",
    medicinesConsumablesCostOfImplantsIfApplicablePleaseSpecify: "500",
    otherHospitalExpenses: "1000",
    allInclusivePackageChargesIfAnyApplicable: "22220",
    sumTotalExpectedCostOfHospitalization: "5000",
    nameOfTheHospital: "Sum Hospital",
    hospitalLocation: "Bhubaneswar",
    hospitalId: "4",
    hospitalMobileNo: "8768867886",
    hospitalEmail: "asif@gmail.com",
    hospitalSumTotalExpectedCostOfHospitalization: "5000",
    dateOfAdmission: "15/07/2025 10:00:00",
    idCardNumber: "ID10001",
    address: "Plot-11, Bhubaneswar, Odisha, 751001",
    duration: "3 days",
    city: "Bhubaneswar",
    state: "Odisha",
    pincode: "751001",
    investigation: "Blood tests, X-ray",
    patientPanNumber: "ABCDE1234F",
    tariff: "Standard",
    rate: "1500",
    surgeryCode: "N/A",
    sumInsured: "100000",
    rohiniId: "R1234",
    dateOfFirstConsultation: "10/07/2025 09:00:00",
    findings: "Mild fever, no complications",
    primaryMember: "Asif Khan",
    familyPhysicianName: "Dr. Meena Singh",
    familyPhysicianContactNumber: "0987654321",
    specialCase: false,
    pastHistoryOfPresentAilment: false,
    intensiveCare: "No",
    presentAilmentDueToPed: false,
    presentAilmentDuration: "311 days",
    daysInIcu: "10",
    diabetesSince: "15/08/2025",
    diabetesSinceTf: true,
    diabetesRemarks: "No diabetes history",
    heartDiseaseSince: "N/A",
    heartDiseaseSinceTf: true,
    heartDiseaseRemarks: "No heart disease",
    hyperlipidemiasSince: "N/A",
    hyperlipidemiasSinceTf: true,
    hyperlipidemiasRemarks: "No hyperlipidemia",
    osteoarthritisSince: "03/2021",
    osteoarthritisSinceTf: "true",
    osteoarthritisRemarks: "Mild knee arthritis",
    hypertensionSince: "04/2022",
    hypertensionSinceTf: true,
    hypertensionRemarks: "Under control",
    asthmaCopdBronchitisSince: "N/A",
    asthmaCopdBronchitisSinceTf: true,
    asthmaCopdBronchitisRemarks: "No respiratory conditions",
    cancerSince: "12-12-2012",
    cancerSinceTf: true,
    cancerRemarks: "No cancer history",
    alcoholDrugabuseSince: "N/A",
    alcoholDrugabuseSinceTf: true,
    alcoholDrugabuseRemarks: "No history of abuse",
    hivstdSince: "N/A",
    hivstdSinceTf: true,
    hivstdRemarks: "No HIV/STD",
    anyOtherailmentSince: "N/A",
    anyOtherailmentSinceTf: "N/A",
    anyOtherailmentRemarks: "No other ailments",
    clinicalFindings: "No abnormality detected",
    otherTreatments: "None",
    dateAndTimeOfSignature: "17/07/2025 15:10:00",
    nameOfTreatingDoctor: "Dr. Rajesh Kumar",
    doctorQualification: "BDS, MDS",
    registrationNumberWithStateCode: "30AB1234",
    hospitalDateAndTimeOfSignature: "17/07/2025 15:15:00",
    documentDetails: "All documents submitted successfully",
    status: "submitted",
    active: true,
    deleted: false,
    createTs: "17/07/2025 15:11:20",
    updateTs: "17/07/2025 15:11:20",
    aggregatorCase: false,
    diabetes: false,
    hypertension: false,
    heartDisease: false,
    hyperlipidemias: false,
    osteoarthritis: false,
    asthmaCopdBronchitis: false,
    cancer: false,
    alcoholDrugabuse: false,
    hivstd: false,
    anyOtherailment: false
  },
  {
    formName: "fhplhealth",
    cashlessFormId: 60,
    currentMedicalInsuranceCompanyName: "FHPL HEALTH",
    payerName: "Asif Khan",
    tollFreePhoneNumber: "9384434576",
    tollFreeTax: "9384434576",
    contactNoOfAttendingRelative: "9384434576",
    currentMedicalCompanyDetails: "",
    hospitalFaxNo: "1505",
    hospitalPhoneNo: "1505",
    rheumatoidArthritisSince: "N/A",
    rheumatoidArthritisSinceTf: "N/A",
    rheumatoidArthritisRemarks: "No rheumatoid disease",
    cerebroVascularSince: "N/A",
    cerebroVascularSinceTf: "N/A",
    cerebroVascularRemarks: "No cerebro vascular disease",
    liverDiseaseSince: "N/A",
    liverDiseaseSinceTf: "N/A",
    liverDiseaseRemarks: "No liver disease",
    kidneyDiseaseSince: "N/A",
    kidneyDiseaseSinceTf: "N/A",
    kidneyDiseaseRemarks: "No liver disease",
    gradeOfSurgery: "Grade II – Intermediate",
    policyId: 12345,
    groupId: 54321,
    corporateId: 7890,
    corporate: "Apex Solutions Group",
    groupName: "Apex Solutions Group",
    corporateEmployeeId: 1001,
    employeeName: "Asif Khan",
    relation: "Self",
    patientName: "Asif",
    patientId: 5001,
    uhid: "5645654",
    contactNo: "7646777891",
    dateOfBirth: "02/06/2020 00:00:00",
    gender: "male",
    age: "5 Y",
    insuranceName: "HealthCare Plus",
    giveDetails: "Patient experienced intermittent fever and body ache for 3 days. Initial diagnosis suggested viral infection. Further tests confirmed no bacterial involvement. Treatment initiated with antipyretics and rest.",
    additionalPayerName: "Family",
    additionalPolicyNumber: "POL1234567",
    email: "asif@gmail.com",
    occupation: "Business Man",
    emergencyContact: "9876543210",
    insuredIdCardNo: "ID123456789",
    policyNumber: "POL09876543219876543210",
    employeeId: "EMP100100",
    memberId: "MEM1001",
    currentlyDoYouHaveAnyOtherMedicalClaimHealthInsurance: "no",
    doYouHaveAFamilyPhysician: "Yes",
    currentPatientAddress: "123, Main Street, Bhubaneswar",
    nameOfTheTreatingDoctor: "Dr. Rajesh Kumar",
    doctorContactNo: "0123456789",
    relevantClinicalFindings: "Normal clinical findings",
    natureOfIllnessWithPresentingComplaints: "Fever, cough, and cold",
    durationOfPresentIllness: "3 days",
    doctorDateOfFirstConsultation: "10/07/2025 09:00:00",
    pastHistoryPresentIllness: "No significant past illness",
    provisionalDiagnosis: "Viral Fever",
    icd10Code: "J11",
    ifInvestigativeOfMedicalManagementProvideDetails: "Blood tests and X-ray",
    routeOfDrugAdministration: "Heart disease",
    proposedLineOfTreatment: "Medical management with antipyretics",
    surgicalNameOfSurgery: "N/A",
    icd10PcsCode: "N/0DTJ0ZZ",
    ifOtherTreatmentDetails: "None",
    howDidInjuryOccur: "N/A",
    dateOfInjury: "01/01/1900 00:00:00",
    isItRta: "no",
    reportedToPolice: "no",
    firNo: "365",
    injuryDueToAlcoholConsumption: "no",
    testsConductedToEstablish: "no",
    expectedDateOfDelivery: "01/01/1900 00:00:00",
    maternityG: "10",
    maternityP: "20",
    maternityL: "30",
    maternityA: "40",
    dateAndTimeOfAdmission: "15/07/2025 10:00:00",
    expectedNoOfDaysStayInHospital: "3",
    isThisAEmergencyOrPlannedEvent: "an emergency",
    roomType: "General Ward",
    perDayRoomRentNursingServiceCharges: "1500",
    expectedCostForInvestigationDiagnostics: "2000",
    icuCharges: "220",
    otCharges: "11230",
    professionalFeesSurgeonAnesthetistFeesConsultationCharges: "1000",
    medicinesConsumablesCostOfImplantsIfApplicablePleaseSpecify: "500",
    otherHospitalExpenses: "1000",
    allInclusivePackageChargesIfAnyApplicable: "22220",
    sumTotalExpectedCostOfHospitalization: "5000",
    nameOfTheHospital: "Sum Hospital",
    hospitalLocation: "Bhubaneswar",
    hospitalId: "4",
    hospitalMobileNo: "8768867886",
    hospitalEmail: "asif@gmail.com",
    hospitalSumTotalExpectedCostOfHospitalization: "5000",
    dateOfAdmission: "15/07/2025 10:00:00",
    idCardNumber: "ID10001",
    address: "Plot-11, Bhubaneswar, Odisha, 751001",
    duration: "3 days",
    city: "Bhubaneswar",
    state: "Odisha",
    pincode: "751001",
    investigation: "Blood tests, X-ray",
    patientPanNumber: "ABCDE1234F",
    tariff: "Standard",
    rate: "1500",
    surgeryCode: "N/A",
    sumInsured: "100000",
    rohiniId: "R1234",
    dateOfFirstConsultation: "10/07/2025 09:00:00",
    findings: "Mild fever, no complications",
    primaryMember: "Asif Khan",
    familyPhysicianName: "Dr. Meena Singh",
    familyPhysicianContactNumber: "0987654321",
    specialCase: false,
    pastHistoryOfPresentAilment: false,
    intensiveCare: "No",
    presentAilmentDueToPed: false,
    presentAilmentDuration: "311 days",
    daysInIcu: "10",
    diabetesSince: "15/08/2025",
    diabetesSinceTf: true,
    diabetesRemarks: "No diabetes history",
    heartDiseaseSince: "N/A",
    heartDiseaseSinceTf: true,
    heartDiseaseRemarks: "No heart disease",
    hyperlipidemiasSince: "N/A",
    hyperlipidemiasSinceTf: true,
    hyperlipidemiasRemarks: "No hyperlipidemia",
    osteoarthritisSince: "03/2021",
    osteoarthritisSinceTf: "true",
    osteoarthritisRemarks: "Mild knee arthritis",
    hypertensionSince: "04/2022",
    hypertensionSinceTf: true,
    hypertensionRemarks: "Under control",
    asthmaCopdBronchitisSince: "N/A",
    asthmaCopdBronchitisSinceTf: true,
    asthmaCopdBronchitisRemarks: "No respiratory conditions",
    cancerSince: "12-12-2012",
    cancerSinceTf: true,
    cancerRemarks: "No cancer history",
    alcoholDrugabuseSince: "N/A",
    alcoholDrugabuseSinceTf: true,
    alcoholDrugabuseRemarks: "No history of abuse",
    hivstdSince: "N/A",
    hivstdSinceTf: true,
    hivstdRemarks: "No HIV/STD",
    anyOtherailmentSince: "N/A",
    anyOtherailmentSinceTf: "N/A",
    anyOtherailmentRemarks: "No other ailments",
    clinicalFindings: "No abnormality detected",
    otherTreatments: "None",
    dateAndTimeOfSignature: "17/07/2025 15:10:00",
    nameOfTreatingDoctor: "Dr. Rajesh Kumar",
    doctorQualification: "BDS, MDS",
    registrationNumberWithStateCode: "30AB1234",
    hospitalDateAndTimeOfSignature: "17/07/2025 15:15:00",
    documentDetails: "All documents submitted successfully",
    status: "submitted",
    active: true,
    deleted: false,
    createTs: "17/07/2025 15:11:20",
    updateTs: "17/07/2025 15:11:20",
    aggregatorCase: false,
    diabetes: false,
    hypertension: false,
    heartDisease: false,
    hyperlipidemias: false,
    osteoarthritis: false,
    asthmaCopdBronchitis: false,
    cancer: false,
    alcoholDrugabuse: false,
    hivstd: false,
    anyOtherailment: false
  },
  {
    formName: "aegon",
    cashlessFormId: 60,
    currentMedicalInsuranceCompanyName: "AEGON",
    payerName: "Asif Khan",
    tollFreePhoneNumber: "9384434576",
    tollFreeTax: "9384434576",
    contactNoOfAttendingRelative: "9384434576",
    currentMedicalCompanyDetails: "",
    hospitalFaxNo: "1505",
    hospitalPhoneNo: "1505",
    rheumatoidArthritisSince: "N/A",
    rheumatoidArthritisSinceTf: "N/A",
    rheumatoidArthritisRemarks: "No rheumatoid disease",
    cerebroVascularSince: "N/A",
    cerebroVascularSinceTf: "N/A",
    cerebroVascularRemarks: "No cerebro vascular disease",
    liverDiseaseSince: "N/A",
    liverDiseaseSinceTf: "N/A",
    liverDiseaseRemarks: "No liver disease",
    kidneyDiseaseSince: "N/A",
    kidneyDiseaseSinceTf: "N/A",
    kidneyDiseaseRemarks: "No liver disease",
    gradeOfSurgery: "Grade II – Intermediate",
    policyId: 12345,
    groupId: 54321,
    corporateId: 7890,
    corporate: "Apex Solutions Group",
    groupName: "Apex Solutions Group",
    corporateEmployeeId: 1001,
    employeeName: "Asif Khan",
    relation: "Self",
    patientName: "Asif",
    patientId: 5001,
    uhid: "5645654",
    contactNo: "7646777891",
    dateOfBirth: "02/06/2020 00:00:00",
    gender: "male",
    age: "5 Y",
    insuranceName: "HealthCare Plus",
    giveDetails: "Patient experienced intermittent fever and body ache for 3 days. Initial diagnosis suggested viral infection. Further tests confirmed no bacterial involvement. Treatment initiated with antipyretics and rest.",
    additionalPayerName: "Family",
    additionalPolicyNumber: "POL1234567",
    email: "asif@gmail.com",
    occupation: "Business Man",
    emergencyContact: "9876543210",
    insuredIdCardNo: "ID123456789",
    policyNumber: "POL09876543219876543210",
    employeeId: "EMP100100",
    memberId: "MEM1001",
    currentlyDoYouHaveAnyOtherMedicalClaimHealthInsurance: "no",
    doYouHaveAFamilyPhysician: "Yes",
    currentPatientAddress: "123, Main Street, Bhubaneswar",
    nameOfTheTreatingDoctor: "Dr. Rajesh Kumar",
    doctorContactNo: "0123456789",
    relevantClinicalFindings: "Normal clinical findings",
    natureOfIllnessWithPresentingComplaints: "Fever, cough, and cold",
    durationOfPresentIllness: "3 days",
    doctorDateOfFirstConsultation: "10/07/2025 09:00:00",
    pastHistoryPresentIllness: "No significant past illness",
    provisionalDiagnosis: "Viral Fever",
    icd10Code: "J11",
    ifInvestigativeOfMedicalManagementProvideDetails: "Blood tests and X-ray",
    routeOfDrugAdministration: "Heart disease",
    proposedLineOfTreatment: "Medical management with antipyretics",
    surgicalNameOfSurgery: "N/A",
    icd10PcsCode: "N/0DTJ0ZZ",
    ifOtherTreatmentDetails: "None",
    howDidInjuryOccur: "N/A",
    dateOfInjury: "01/01/1900 00:00:00",
    isItRta: "no",
    reportedToPolice: "no",
    firNo: "365",
    injuryDueToAlcoholConsumption: "no",
    testsConductedToEstablish: "no",
    expectedDateOfDelivery: "01/01/1900 00:00:00",
    maternityG: "10",
    maternityP: "20",
    maternityL: "30",
    maternityA: "40",
    dateAndTimeOfAdmission: "15/07/2025 10:00:00",
    expectedNoOfDaysStayInHospital: "3",
    isThisAEmergencyOrPlannedEvent: "an emergency",
    roomType: "General Ward",
    perDayRoomRentNursingServiceCharges: "1500",
    expectedCostForInvestigationDiagnostics: "2000",
    icuCharges: "220",
    otCharges: "11230",
    professionalFeesSurgeonAnesthetistFeesConsultationCharges: "1000",
    medicinesConsumablesCostOfImplantsIfApplicablePleaseSpecify: "500",
    otherHospitalExpenses: "1000",
    allInclusivePackageChargesIfAnyApplicable: "22220",
    sumTotalExpectedCostOfHospitalization: "5000",
    nameOfTheHospital: "Sum Hospital",
    hospitalLocation: "Bhubaneswar",
    hospitalId: "4",
    hospitalMobileNo: "8768867886",
    hospitalEmail: "asif@gmail.com",
    hospitalSumTotalExpectedCostOfHospitalization: "5000",
    dateOfAdmission: "15/07/2025 10:00:00",
    idCardNumber: "ID10001",
    address: "Plot-11, Bhubaneswar, Odisha, 751001",
    duration: "3 days",
    city: "Bhubaneswar",
    state: "Odisha",
    pincode: "751001",
    investigation: "Blood tests, X-ray",
    patientPanNumber: "ABCDE1234F",
    tariff: "Standard",
    rate: "1500",
    surgeryCode: "N/A",
    sumInsured: "100000",
    rohiniId: "R1234",
    dateOfFirstConsultation: "10/07/2025 09:00:00",
    findings: "Mild fever, no complications",
    primaryMember: "Asif Khan",
    familyPhysicianName: "Dr. Meena Singh",
    familyPhysicianContactNumber: "0987654321",
    specialCase: false,
    pastHistoryOfPresentAilment: false,
    intensiveCare: "No",
    presentAilmentDueToPed: false,
    presentAilmentDuration: "311 days",
    daysInIcu: "10",
    diabetesSince: "15/08/2025",
    diabetesSinceTf: true,
    diabetesRemarks: "No diabetes history",
    heartDiseaseSince: "N/A",
    heartDiseaseSinceTf: true,
    heartDiseaseRemarks: "No heart disease",
    hyperlipidemiasSince: "N/A",
    hyperlipidemiasSinceTf: true,
    hyperlipidemiasRemarks: "No hyperlipidemia",
    osteoarthritisSince: "03/2021",
    osteoarthritisSinceTf: "true",
    osteoarthritisRemarks: "Mild knee arthritis",
    hypertensionSince: "04/2022",
    hypertensionSinceTf: true,
    hypertensionRemarks: "Under control",
    asthmaCopdBronchitisSince: "N/A",
    asthmaCopdBronchitisSinceTf: true,
    asthmaCopdBronchitisRemarks: "No respiratory conditions",
    cancerSince: "12-12-2012",
    cancerSinceTf: true,
    cancerRemarks: "No cancer history",
    alcoholDrugabuseSince: "N/A",
    alcoholDrugabuseSinceTf: true,
    alcoholDrugabuseRemarks: "No history of abuse",
    hivstdSince: "N/A",
    hivstdSinceTf: true,
    hivstdRemarks: "No HIV/STD",
    anyOtherailmentSince: "N/A",
    anyOtherailmentSinceTf: "N/A",
    anyOtherailmentRemarks: "No other ailments",
    clinicalFindings: "No abnormality detected",
    otherTreatments: "None",
    dateAndTimeOfSignature: "17/07/2025 15:10:00",
    nameOfTreatingDoctor: "Dr. Rajesh Kumar",
    doctorQualification: "BDS, MDS",
    registrationNumberWithStateCode: "30AB1234",
    hospitalDateAndTimeOfSignature: "17/07/2025 15:15:00",
    documentDetails: "All documents submitted successfully",
    status: "submitted",
    active: true,
    deleted: false,
    createTs: "17/07/2025 15:11:20",
    updateTs: "17/07/2025 15:11:20",
    aggregatorCase: false,
    diabetes: false,
    hypertension: false,
    heartDisease: false,
    hyperlipidemias: false,
    osteoarthritis: false,
    asthmaCopdBronchitis: false,
    cancer: false,
    alcoholDrugabuse: false,
    hivstd: false,
    anyOtherailment: false
  },
  {
    formName: "star health",
    cashlessFormId: 60,
    currentMedicalInsuranceCompanyName: "STAR HEALTH",
    payerName: "Asif Khan",
    tollFreePhoneNumber: "9384434576",
    tollFreeTax: "9384434576",
    contactNoOfAttendingRelative: "9384434576",
    currentMedicalCompanyDetails: "",
    hospitalFaxNo: "1505",
    hospitalPhoneNo: "1505",
    rheumatoidArthritisSince: "N/A",
    rheumatoidArthritisSinceTf: "N/A",
    rheumatoidArthritisRemarks: "No rheumatoid disease",
    cerebroVascularSince: "N/A",
    cerebroVascularSinceTf: "N/A",
    cerebroVascularRemarks: "No cerebro vascular disease",
    liverDiseaseSince: "N/A",
    liverDiseaseSinceTf: "N/A",
    liverDiseaseRemarks: "No liver disease",
    kidneyDiseaseSince: "N/A",
    kidneyDiseaseSinceTf: "N/A",
    kidneyDiseaseRemarks: "No liver disease",
    gradeOfSurgery: "Grade II – Intermediate",
    policyId: 12345,
    groupId: 54321,
    corporateId: 7890,
    corporate: "Apex Solutions Group",
    groupName: "Apex Solutions Group",
    corporateEmployeeId: 1001,
    employeeName: "Asif Khan",
    relation: "Self",
    patientName: "Asif",
    patientId: 5001,
    uhid: "5645654",
    contactNo: "7646777891",
    dateOfBirth: "02/06/2020 00:00:00",
    gender: "male",
    age: "5 Y",
    insuranceName: "HealthCare Plus",
    giveDetails: "Patient experienced intermittent fever and body ache for 3 days. Initial diagnosis suggested viral infection. Further tests confirmed no bacterial involvement. Treatment initiated with antipyretics and rest.",
    additionalPayerName: "Family",
    additionalPolicyNumber: "POL1234567",
    email: "asif@gmail.com",
    occupation: "Business Man",
    emergencyContact: "9876543210",
    insuredIdCardNo: "ID123456789",
    policyNumber: "POL09876543219876543210",
    employeeId: "EMP100100",
    memberId: "MEM1001",
    currentlyDoYouHaveAnyOtherMedicalClaimHealthInsurance: "no",
    doYouHaveAFamilyPhysician: "Yes",
    currentPatientAddress: "123, Main Street, Bhubaneswar",
    nameOfTheTreatingDoctor: "Dr. Rajesh Kumar",
    doctorContactNo: "0123456789",
    relevantClinicalFindings: "Normal clinical findings",
    natureOfIllnessWithPresentingComplaints: "Fever, cough, and cold",
    durationOfPresentIllness: "3 days",
    doctorDateOfFirstConsultation: "10/07/2025 09:00:00",
    pastHistoryPresentIllness: "No significant past illness",
    provisionalDiagnosis: "Viral Fever",
    icd10Code: "J11",
    ifInvestigativeOfMedicalManagementProvideDetails: "Blood tests and X-ray",
    routeOfDrugAdministration: "Heart disease",
    proposedLineOfTreatment: "Medical management with antipyretics",
    surgicalNameOfSurgery: "N/A",
    icd10PcsCode: "N/0DTJ0ZZ",
    ifOtherTreatmentDetails: "None",
    howDidInjuryOccur: "N/A",
    dateOfInjury: "01/01/1900 00:00:00",
    isItRta: "no",
    reportedToPolice: "no",
    firNo: "365",
    injuryDueToAlcoholConsumption: "no",
    testsConductedToEstablish: "no",
    expectedDateOfDelivery: "01/01/1900 00:00:00",
    maternityG: "10",
    maternityP: "20",
    maternityL: "30",
    maternityA: "40",
    dateAndTimeOfAdmission: "15/07/2025 10:00:00",
    expectedNoOfDaysStayInHospital: "3",
    isThisAEmergencyOrPlannedEvent: "an emergency",
    roomType: "General Ward",
    perDayRoomRentNursingServiceCharges: "1500",
    expectedCostForInvestigationDiagnostics: "2000",
    icuCharges: "220",
    otCharges: "11230",
    professionalFeesSurgeonAnesthetistFeesConsultationCharges: "1000",
    medicinesConsumablesCostOfImplantsIfApplicablePleaseSpecify: "500",
    otherHospitalExpenses: "1000",
    allInclusivePackageChargesIfAnyApplicable: "22220",
    sumTotalExpectedCostOfHospitalization: "5000",
    nameOfTheHospital: "Sum Hospital",
    hospitalLocation: "Bhubaneswar",
    hospitalId: "4",
    hospitalMobileNo: "8768867886",
    hospitalEmail: "asif@gmail.com",
    hospitalSumTotalExpectedCostOfHospitalization: "5000",
    dateOfAdmission: "15/07/2025 10:00:00",
    idCardNumber: "ID10001",
    address: "Plot-11, Bhubaneswar, Odisha, 751001",
    duration: "3 days",
    city: "Bhubaneswar",
    state: "Odisha",
    pincode: "751001",
    investigation: "Blood tests, X-ray",
    patientPanNumber: "ABCDE1234F",
    tariff: "Standard",
    rate: "1500",
    surgeryCode: "N/A",
    sumInsured: "100000",
    rohiniId: "R1234",
    dateOfFirstConsultation: "10/07/2025 09:00:00",
    findings: "Mild fever, no complications",
    primaryMember: "Asif Khan",
    familyPhysicianName: "Dr. Meena Singh",
    familyPhysicianContactNumber: "0987654321",
    specialCase: false,
    pastHistoryOfPresentAilment: false,
    intensiveCare: "No",
    presentAilmentDueToPed: false,
    presentAilmentDuration: "311 days",
    daysInIcu: "10",
    diabetesSince: "15/08/2025",
    diabetesSinceTf: true,
    diabetesRemarks: "No diabetes history",
    heartDiseaseSince: "N/A",
    heartDiseaseSinceTf: true,
    heartDiseaseRemarks: "No heart disease",
    hyperlipidemiasSince: "N/A",
    hyperlipidemiasSinceTf: true,
    hyperlipidemiasRemarks: "No hyperlipidemia",
    osteoarthritisSince: "03/2021",
    osteoarthritisSinceTf: "true",
    osteoarthritisRemarks: "Mild knee arthritis",
    hypertensionSince: "04/2022",
    hypertensionSinceTf: true,
    hypertensionRemarks: "Under control",
    asthmaCopdBronchitisSince: "N/A",
    asthmaCopdBronchitisSinceTf: true,
    asthmaCopdBronchitisRemarks: "No respiratory conditions",
    cancerSince: "12-12-2012",
    cancerSinceTf: true,
    cancerRemarks: "No cancer history",
    alcoholDrugabuseSince: "N/A",
    alcoholDrugabuseSinceTf: true,
    alcoholDrugabuseRemarks: "No history of abuse",
    hivstdSince: "N/A",
    hivstdSinceTf: true,
    hivstdRemarks: "No HIV/STD",
    anyOtherailmentSince: "N/A",
    anyOtherailmentSinceTf: "N/A",
    anyOtherailmentRemarks: "No other ailments",
    clinicalFindings: "No abnormality detected",
    otherTreatments: "None",
    dateAndTimeOfSignature: "17/07/2025 15:10:00",
    nameOfTreatingDoctor: "Dr. Rajesh Kumar",
    doctorQualification: "BDS, MDS",
    registrationNumberWithStateCode: "30AB1234",
    hospitalDateAndTimeOfSignature: "17/07/2025 15:15:00",
    documentDetails: "All documents submitted successfully",
    status: "submitted",
    active: true,
    deleted: false,
    createTs: "17/07/2025 15:11:20",
    updateTs: "17/07/2025 15:11:20",
    aggregatorCase: false,
    diabetes: false,
    hypertension: false,
    heartDisease: false,
    hyperlipidemias: false,
    osteoarthritis: false,
    asthmaCopdBronchitis: false,
    cancer: false,
    alcoholDrugabuse: false,
    hivstd: false,
    anyOtherailment: false
  }
];