import { Geist, Geist_Mono, Inter, Lato, Nunito } from "next/font/google";
import "./globals.css";
import StoreProvider from "@/redux/StoreProvider";
import DashboardLayout from "./components/DashboardLayout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
});

const lato = Lato({
  variable: "--font-lato",
  subsets: ["latin"],
  weight: ["400"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["400", "500", "600"],
});

export const metadata = {
  title: "HCRM",
  description: "Generated by MSH",
  openGraph: {
    title: "HCRM",
    description: "Created by MSH",
    images: [
      "https://www.google.com/imgres?q=my%20smart%20health&imgurl=https%3A%2F%2Fmedia.licdn.com%2Fdms%2Fimage%2Fv2%2FC4D0BAQHiPBnfYb0Asg%2Fcompany-logo_200_200%2Fcompany-logo_200_200%2F0%2F1630580184740%3Fe%3D2147483647%26v%3Dbeta%26t%3D0oOD1xPa5SfiSnvu9swVewakC0BVnBqi7rUkbVn4mtw&imgrefurl=https%3A%2F%2Fin.linkedin.com%2Fcompany%2Fmysmarthealth&docid=O61YAF27PyoAPM&tbnid=4dfhfDR4hDmx6M&vet=12ahUKEwi9g8ij39yOAxUPT2wGHRptIlgQM3oECBQQAA..i&w=200&h=200&hcb=2&ved=2ahUKEwi9g8ij39yOAxUPT2wGHRptIlgQM3oECBQQAA",
    ],
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable}
         ${geistMono.variable}
         ${nunito.variable} ${lato.variable} 
          ${inter.variable} 
         antialiased`}
      >
        <StoreProvider>{children}</StoreProvider>
      </body>
    </html>
  );
}
